'use client';

import { useState } from 'react';
import { DatePresetButtons } from '@/components/DatePresetButtons';
import { formatDate, formatCurrency } from '@/lib/utils';
import { ReportPayment, User } from '@/types';

interface CashierReportsProps {
  user: User | null;
}

export function CashierReports({ user }: CashierReportsProps) {
  const [fromDate, setFromDate] = useState('');
  const [toDate, setToDate] = useState('');
  const [collectionsData, setCollectionsData] = useState<ReportPayment[]>([]);
  const [loading, setLoading] = useState(false);

  const fetchReport = async () => {
    if (!fromDate || !toDate) { alert('Please select both From and To dates'); return; }
    setLoading(true);
    try {
      const params = new URLSearchParams({ from: fromDate, to: toDate });
      const response = await fetch(`/api/reports/collections?${params}`);
      if (response.ok) {
        const data = await response.json();
        // API returns { payments, totals } — extract the payments array
        setCollectionsData(Array.isArray(data) ? data : data.payments ?? []);
      }
    } catch (error) {
      console.error('Error fetching report:', error);
    } finally {
      setLoading(false);
    }
  };

  const exportToPDF = async () => {
    const jsPDFModule = await import('jspdf');
    const jsPDF = jsPDFModule.default;
    await import('jspdf-autotable');

    const doc = new jsPDF();
    doc.setFontSize(18);
    doc.text('Daily Collection Report', 14, 22);
    doc.setFontSize(11);
    doc.text(`Date Range: ${fromDate} to ${toDate}`, 14, 32);
    doc.text(`Generated by: ${user?.name}`, 14, 40);

    const sortedData = [...collectionsData].sort((a, b) => {
      const sc = a.appointment.sacramentType.localeCompare(b.appointment.sacramentType);
      if (sc !== 0) return sc;
      return new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime();
    });

    const groupedByDate: { [key: string]: ReportPayment[] } = {};
    sortedData.forEach((payment) => {
      const date = new Date(payment.createdAt).toISOString().split('T')[0];
      if (!groupedByDate[date]) groupedByDate[date] = [];
      groupedByDate[date].push(payment);
    });

    let yPos = 50;
    let grandTotal = 0;

    Object.entries(groupedByDate).forEach(([date, datePayments]) => {
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text(formatDate(date), 14, yPos);
      yPos += 6;

      const tableData = datePayments.map((payment) => [
        payment.appointment.participantName,
        payment.appointment.sacramentType,
        payment.paymentMethod,
        payment.receiptNumber,
        Math.abs(payment.amount).toFixed(2),
      ]);

      const dateTotal = datePayments.reduce((sum, p) => sum + Math.abs(p.amount), 0);
      grandTotal += dateTotal;

      (doc as any).autoTable({
        startY: yPos,
        head: [['Participant', 'Sacrament', 'Method', 'Receipt #', 'Amount']],
        body: tableData,
        theme: 'striped',
        headStyles: { fillColor: [41, 128, 185] },
        styles: { fontSize: 9 },
        columnStyles: { 4: { halign: 'right' } },
        margin: { left: 14 },
      });

      yPos = (doc as any).lastAutoTable.finalY + 5;
      doc.setFont('helvetica', 'bold');
      doc.text(`Subtotal: PHP ${dateTotal.toFixed(2)}`, 150, yPos, { align: 'right' });
      yPos += 10;

      if (yPos > 260) { doc.addPage(); yPos = 20; }
    });

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(`Grand Total: PHP ${grandTotal.toFixed(2)}`, 150, yPos + 5, { align: 'right' });
    doc.save(`daily-collection-report-${fromDate}-to-${toDate}.pdf`);
  };

  // Group and render
  const sortedData = [...collectionsData].sort((a, b) => {
    const sc = a.appointment.sacramentType.localeCompare(b.appointment.sacramentType);
    if (sc !== 0) return sc;
    return new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime();
  });

  const groupedByDate: { [key: string]: ReportPayment[] } = {};
  sortedData.forEach((payment) => {
    const date = new Date(payment.createdAt).toISOString().split('T')[0];
    if (!groupedByDate[date]) groupedByDate[date] = [];
    groupedByDate[date].push(payment);
  });

  let grandTotal = 0;
  Object.values(groupedByDate).forEach((payments) => {
    grandTotal += payments.reduce((sum, p) => sum + Math.abs(p.amount), 0);
  });

  return (
    <div className="space-y-6">
      <div className="bg-white p-6 rounded-lg shadow">
        <h2 className="text-xl font-bold mb-4">Daily Collection Report</h2>
        <DatePresetButtons onSetDates={(f, t) => { setFromDate(f); setToDate(t); }} />
        <div className="flex flex-wrap gap-4 items-end">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">From Date</label>
            <input type="date" value={fromDate} onChange={(e) => setFromDate(e.target.value)} className="px-3 py-2 border rounded-lg" />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">To Date</label>
            <input type="date" value={toDate} onChange={(e) => setToDate(e.target.value)} className="px-3 py-2 border rounded-lg" />
          </div>
          <button onClick={fetchReport} disabled={loading} className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 disabled:bg-gray-400">
            {loading ? 'Loading...' : 'Generate Report'}
          </button>
          {collectionsData.length > 0 && (
            <button onClick={exportToPDF} className="bg-green-600 text-white px-4 py-2 rounded-lg hover:bg-green-700">
              Export to PDF
            </button>
          )}
        </div>
      </div>

      {collectionsData.length > 0 && (
        <div className="bg-white p-6 rounded-lg shadow">
          <h3 className="text-lg font-bold mb-4">Collection Results</h3>
          {Object.entries(groupedByDate).map(([date, datePayments]) => {
            const dateTotal = datePayments.reduce((sum, p) => sum + Math.abs(p.amount), 0);
            return (
              <div key={date} className="mb-6">
                <h4 className="font-semibold text-gray-800 mb-2 bg-gray-100 p-2 rounded">{formatDate(date)}</h4>
                <div className="overflow-x-auto">
                  <table className="min-w-full divide-y divide-gray-200">
                    <thead className="bg-gray-50">
                      <tr>
                        <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Participant</th>
                        <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Sacrament</th>
                        <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Method</th>
                        <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Receipt #</th>
                        <th className="px-4 py-2 text-right text-xs font-medium text-gray-500 uppercase">Amount</th>
                      </tr>
                    </thead>
                    <tbody className="bg-white divide-y divide-gray-200">
                      {datePayments.map((payment) => (
                        <tr key={payment.id}>
                          <td className="px-4 py-2 text-sm">{payment.appointment.participantName}</td>
                          <td className="px-4 py-2 text-sm">{payment.appointment.sacramentType}</td>
                          <td className="px-4 py-2 text-sm">{payment.paymentMethod}</td>
                          <td className="px-4 py-2 text-sm">{payment.receiptNumber}</td>
                          <td className="px-4 py-2 text-sm text-right font-medium">{formatCurrency(Math.abs(payment.amount))}</td>
                        </tr>
                      ))}
                    </tbody>
                    <tfoot>
                      <tr className="bg-gray-50">
                        <td colSpan={4} className="px-4 py-2 text-sm font-semibold text-right">Subtotal:</td>
                        <td className="px-4 py-2 text-sm font-semibold text-right">{formatCurrency(dateTotal)}</td>
                      </tr>
                    </tfoot>
                  </table>
                </div>
              </div>
            );
          })}
          <div className="border-t-2 border-gray-300 pt-4 mt-4">
            <div className="flex justify-end">
              <span className="text-lg font-bold">Grand Total: {formatCurrency(grandTotal)}</span>
            </div>
          </div>
        </div>
      )}

      {collectionsData.length === 0 && fromDate && toDate && !loading && (
        <div className="bg-white p-6 rounded-lg shadow text-center text-gray-500">
          No collection data found for the selected date range.
        </div>
      )}
    </div>
  );
}
